apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-cfg
  namespace: monitoring
data:
  config.yaml: |
    logLevel: info
    logFormat: json
    trottlePeriod: 20
    route:
      routes:
        - match:
            - receiver: "loki"
    receivers:
      - name: "loki"
        webhook:
          endpoint: 'http://loki-gateway/loki/api/v1/push'
          headers:
            Content-Type: application/json
            User-Agent: kube-event-exporter
          layout:
            streams:
              - stream:
                  kind: kube-event
                  namespace: '{{ .InvolvedObject.Namespace }}'
                  type: '{{ .Type }}'
                values:
                  - - "{{ mul .GetTimestampMs 1000000 }}"
                    - 'level={{ lower .Type | replace "normal" "notice" }} namespace={{ .InvolvedObject.Namespace }} object={{ .InvolvedObject.Kind }}/{{ .InvolvedObject.Name }} reason={{ .Reason }} message={{ quote .Message }}'
